name: Fetch and Merge EPG

on:
  schedule:
    - cron: "0 */6 * * *"   # run every 6 hours
  workflow_dispatch:        # allow manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2

      - name: Run EPG Fetch + Merge
        run: pwsh ./scripts/Get-EPG-Countries.ps1 -ExcludeFile ./configs/exclude_channels.txt

      - name: Commit and Push updated EPG files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/output/*.xml logs/open-epg.log.txt
          git commit -m "Update per-country EPG files"
          git push
